const {test}=require('node:test'),assert=require('node:assert/strict');
const {createVideoCache,createRouteCooldown}=require('../video-cache.js');
function setup(limit=8){const data=new Map();let now=1;const store={list:async()=>[...data.values()].map(({blob,...r})=>r),get:async k=>data.get(k),put:async r=>data.set(r.key,r),remove:async k=>data.delete(k),clear:async()=>data.clear()};const cache=createVideoCache({store,limit:()=>limit,now:()=>now});return {cache,data,store,tick:()=>now++,limit:n=>limit=n};}
test('completed clips reopen without network and are isolated by account',async()=>{const {cache}=setup();assert.equal(await cache.put('a',new Blob(['abcd']),{size:4,modifiedTime:'v1'},'accountA'),true);const blob=await cache.get('a',{size:4,modifiedTime:'v1'},'accountA');assert.equal(await blob.text(),'abcd');assert.equal(await cache.get('a',{},'accountB'),null);});
test('metadata changes and incomplete downloads are not reused',async()=>{const {cache,data}=setup();assert.equal(await cache.put('a',new Blob(['abc']),{size:4},'public'),false);assert.equal(data.size,0);await cache.put('a',new Blob(['abcd']),{size:4,modifiedTime:'v1'},'public');assert.equal(await cache.get('a',{size:4,modifiedTime:'v2'},'public'),null);assert.equal(data.size,0);});
test('least recently opened clips are evicted and oversized clips are skipped',async()=>{const {cache,data,tick}=setup();await cache.put('a',new Blob(['aaaa']),{},'public');tick();await cache.put('b',new Blob(['bbbb']),{},'public');tick();await cache.get('a',{},'public');tick();await cache.put('c',new Blob(['cccc']),{},'public');assert.equal(await cache.get('b',{},'public'),null);assert.equal(data.size,2);assert.equal(await cache.put('large',new Blob(['123456789']),{},'public'),false);assert.equal(data.size,2);});
test('lowering limit trims immediately and disabling removes all cached clips',async()=>{const s=setup();await s.cache.put('a',new Blob(['aaaa']),{},'public');await s.cache.put('b',new Blob(['bbbb']),{},'public');s.limit(4);await s.cache.trim();assert.equal((await s.cache.stats()).bytes,4);s.limit(0);await s.cache.trim();assert.equal(s.data.size,0);});
test('quota failures and unavailable storage never break playback',async()=>{const {cache,store}=setup();store.put=async()=>{throw new Error('QuotaExceededError')};assert.equal(await cache.put('a',new Blob(['aaaa']),{},'public'),false);const unsupported=createVideoCache({store:null,limit:()=>8});assert.equal(await unsupported.get('a',{},'public'),null);assert.equal(await unsupported.put('a',new Blob(['aaaa']),{},'public'),false);});
test('HTML and JSON errors are never kept as completed clips',async()=>{const {cache,data}=setup();assert.equal(await cache.put('a',new Blob(['oops'],{type:'text/html'}),{},'public'),false);assert.equal(await cache.put('b',new Blob(['oops'],{type:'application/json'}),{},'public'),false);assert.equal(data.size,0);});
test('clear invalidates pending saves so logout cannot resurrect a clip',async()=>{const {cache,store,data}=setup();let release;store.put=r=>new Promise(resolve=>{release=()=>{data.set(r.key,r);resolve()}});const save=cache.put('a',new Blob(['aaaa']),{},'public');while(!release)await new Promise(r=>setImmediate(r));const clear=cache.clear();release();await Promise.all([save,clear]);assert.equal(data.size,0);});
test('failed routes cool down per file and auth mode and manual retry resets them',()=>{let now=100;const routes=createRouteCooldown(()=>now);routes.fail('a','signedin','worker');assert.equal(routes.blocked('a','signedin','worker'),true);assert.equal(routes.blocked('b','signedin','worker'),false);assert.equal(routes.blocked('a','public','worker'),false);routes.clear('a','signedin');assert.equal(routes.blocked('a','signedin','worker'),false);routes.fail('a','signedin','worker');now+=300001;assert.equal(routes.blocked('a','signedin','worker'),false);});
const fs=require('node:fs'),vm=require('node:vm'),html=fs.readFileSync('index.html','utf8');
function fn(name){const start=html.indexOf('      function '+name+'(');assert(start>=0,name);return html.slice(start,html.indexOf('\n      }',start)+8);}
function player(){let streams=0;const played=[];const ctx={videoCache:{get:async()=>new Blob(['abcd']),remove:async()=>{}},videoCacheScope:()=> 'public',fileMetaOf:()=>({size:4}),mediaSession:1,videoAttempt:1,vidCurrentId:'a',accessToken:null,videoModal:{classList:{contains:()=>true}},vidPlayer:{style:{},removeAttribute(){}},URL:{createObjectURL:()=> 'blob:cached'},revokeCurrentVideo(){},tryVideoSrc:(url,fail)=>played.push({url,fail}),tryStreamDirect:()=>streams++,setVideoStatus(){},setTimeout,clearTimeout};vm.createContext(ctx);vm.runInContext(fn('startVideoPlayback'),ctx);return {ctx,played,streams:()=>streams};}
test('opening a cached clip starts local playback without a network stream',async()=>{const p=player();await p.ctx.startVideoPlayback('a');assert.equal(p.played[0].url,'blob:cached');assert.equal(p.streams(),0);});
test('late cache lookup after close or file switch cannot play',async()=>{const p=player();let resolve;p.ctx.videoCache.get=()=>new Promise(r=>resolve=r);const pending=p.ctx.startVideoPlayback('a');p.ctx.mediaSession++;resolve(new Blob(['abcd']));await pending;assert.equal(p.played.length,0);assert.equal(p.streams(),0);});
test('missing or unplayable local clip falls back to streaming',async()=>{const p=player();p.ctx.videoCache.get=async()=>null;await p.ctx.startVideoPlayback('a');assert.equal(p.streams(),1);const q=player();await q.ctx.startVideoPlayback('a');await q.played[0].fail();assert.equal(q.streams(),1);});
